version: '3.4'
services:
  db:
    build:
      context: ./db
    networks:
      - bookings
    expose:
      - '5432'
    ports:
      - 3333:5432

  app:
    build:
      context: .
      target: release
    depends_on:
      - db
    networks:
      - bookings
    working_dir: /app
    image: dskly
    command: npm start
    ports:
      - 8080:8080
    environment:
      - BUILD_ENV=DEVELOPMENT
      - DB_HOST=db
      - DB_PASSWORD=password
      - DB_NAME=desk_bookings
      - NODE_ENV=local

networks:
  bookings:
